// Script para inserção dos 15 animais via API do Supabase (Opcional)
// Alternativamente, execute o script 'supabase/schema.sql' diretamente no SQL Editor do Supabase Dashboard.
import 'package:supabase/supabase.dart';

void main(List<String> args) async {
  final supabaseUrl = args.isNotEmpty ? args[0] : 'https://SEU_PROJETO.supabase.co';
  final serviceRoleOrAnonKey = args.length > 1 ? args[1] : 'SUA_CHAVE_AQUI';

  if (supabaseUrl.contains('SEU_PROJETO') || serviceRoleOrAnonKey.contains('SUA_CHAVE')) {
    print('----------------------------------------------------------------------');
    print('USO: dart run tool/seed_supabase.dart <SUPABASE_URL> <SUPABASE_ANON_KEY>');
    print('Ou simplesmente execute o arquivo supabase/schema.sql no SQL Editor do Supabase.');
    print('----------------------------------------------------------------------');
    return;
  }

  print('Conectando ao Supabase em: $supabaseUrl...');
  final client = SupabaseClient(supabaseUrl, serviceRoleOrAnonKey);

  final animals = [
    {
      'name': 'Thor',
      'species': 'cao',
      'breed': 'Labrador Retriever',
      'age_group': 'jovem',
      'size': 'grande',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Thor é super dócil, brincalhão e adora correr no parque. Convive muito bem com crianças e outros cães.',
      'city': 'São Paulo',
      'state': 'SP',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Mimi',
      'species': 'gato',
      'breed': 'SRD (Vira-lata)',
      'age_group': 'filhote',
      'size': 'pequeno',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': false,
      'is_dewormed': true,
      'temperament_notes': 'Gatinha carinhosa, ronrona o tempo todo e adora colo. Resgatada de uma caixa de papelão.',
      'city': 'Rio de Janeiro',
      'state': 'RJ',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Bob',
      'species': 'cao',
      'breed': 'Caramelo (SRD)',
      'age_group': 'adulto',
      'size': 'medio',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'O clássico vira-lata caramelo brasileiro! Tranquilo, companheiro para passeios e muito protetor da casa.',
      'city': 'Curitiba',
      'state': 'PR',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Luna',
      'species': 'gato',
      'breed': 'Persa Mestiça',
      'age_group': 'jovem',
      'size': 'pequeno',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Tranquila e silenciosa. Gosta de passar a tarde na janela observando o movimento. Já castrada.',
      'city': 'Belo Horizonte',
      'state': 'MG',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Rex',
      'species': 'cao',
      'breed': 'Pastor Alemão Mestiço',
      'age_group': 'adulto',
      'size': 'grande',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Excelente cão de guarda e companhia. Leal, obediente, sabe sentar e dar a pata.',
      'city': 'Porto Alegre',
      'state': 'RS',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1589941013453-ec89f33b5455?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Mel',
      'species': 'cao',
      'breed': 'Golden Retriever',
      'age_group': 'adulto',
      'size': 'grande',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Uma doçura de cadela! Ama água, busca bolinha e é perfeita para família com crianças.',
      'city': 'Salvador',
      'state': 'BA',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Nina',
      'species': 'gato',
      'breed': 'Tricolor (SRD)',
      'age_group': 'adulto',
      'size': 'pequeno',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Gata tricolor linda e graciosa. Gosta de sachê e brinquedos com penas. Muito limpa e educada.',
      'city': 'Fortaleza',
      'state': 'CE',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Bart',
      'species': 'cao',
      'breed': 'Beagle',
      'age_group': 'jovem',
      'size': 'medio',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Curioso, farejador nato e cheio de energia! Precisa de tutor que goste de fazer caminhadas.',
      'city': 'Recife',
      'state': 'PE',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Zoe',
      'species': 'gato',
      'breed': 'Siamês',
      'age_group': 'adulto',
      'size': 'pequeno',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Olhos azuis penetrantes e muito comunicativa. Gosta de conversar com os tutores e deitar no colo.',
      'city': 'Brasília',
      'state': 'DF',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Max',
      'species': 'cao',
      'breed': 'Poodle Mestiço',
      'age_group': 'idoso',
      'size': 'pequeno',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Cãozinho idoso, extremamente calmo, quase não late. Ideal para apartamento ou tutores que trabalham de home office.',
      'city': 'Manaus',
      'state': 'AM',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Lola',
      'species': 'cao',
      'breed': 'SRD (Vira-lata)',
      'age_group': 'filhote',
      'size': 'medio',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': false,
      'is_dewormed': true,
      'temperament_notes': 'Filhotinha resgatada de terreno baldio. Saudável, vacinas em dia e já comendo ração seca.',
      'city': 'Campinas',
      'state': 'SP',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Frajola',
      'species': 'gato',
      'breed': 'Frajolinha (Preto e Branco)',
      'age_group': 'jovem',
      'size': 'pequeno',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Gatinho ativo e muito brincalhão. Adora caçar bolinhas de papel e subir no arranhador.',
      'city': 'Santos',
      'state': 'SP',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Duque',
      'species': 'cao',
      'breed': 'Rottweiler Mestiço',
      'age_group': 'adulto',
      'size': 'grande',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Porte imponente mas coração mole! Adora carinho na barriga e se dá muito bem com a família.',
      'city': 'Goiânia',
      'state': 'GO',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Brisa',
      'species': 'gato',
      'breed': 'Maine Coon Mestiça',
      'age_group': 'adulto',
      'size': 'medio',
      'gender': 'femea',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Pelagem longa e macia, porte elegante. Dócil, calma e muito amorosa.',
      'city': 'Florianópolis',
      'state': 'SC',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1561948955-570b270e7c36?auto=format&fit=crop&w=800&q=80'],
    },
    {
      'name': 'Pipoca',
      'species': 'cao',
      'breed': 'Shih Tzu Mestiço',
      'age_group': 'jovem',
      'size': 'pequeno',
      'gender': 'macho',
      'is_vaccinated': true,
      'is_castrated': true,
      'is_dewormed': true,
      'temperament_notes': 'Muito simpático e sociável com outros pets. Pêlo tosado recentemente, pronto para um novo lar.',
      'city': 'Natal',
      'state': 'RN',
      'status': 'disponivel',
      'image_urls': ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80'],
    }
  ];

  print('Inserindo 15 animais no Supabase...');
  try {
    for (final animal in animals) {
      await client.from('animals').insert(animal);
      print('Animal inserido: ${animal['name']}');
    }
    print('Sucesso! Todos os 15 animais foram inseridos.');
  } catch (e) {
    print('Erro ao inserir: $e');
  }
}
